/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IMaribFirstContentData } from './marib-first-content.data';
import { IMaribFirstContentProps } from './marib-first-content.props.autogenerated';

export interface IMaribFirstContentViewProps extends IMaribFirstContentProps<IMaribFirstContentData> {

}

/**
 *
 * MaribFirstContent component
 * @extends {React.PureComponent<IMaribFirstContentProps<IMaribFirstContentData>>}
 */
class MaribFirstContent extends React.PureComponent<IMaribFirstContentProps<IMaribFirstContentData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default MaribFirstContent;
