/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { ISecondContainerData } from './second-container.data';
import { ISecondContainerProps } from './second-container.props.autogenerated';

/**
 *
 * SecondContainer component
 * @extends {React.PureComponent<ISecondContainerProps<ISecondContainerData>>}
 */
export default class SecondContainer extends React.PureComponent<ISecondContainerProps<ISecondContainerData>> {
    public render(): JSX.Element {
        // const { config, resources } = this.props;

        return (
            <div className='row'>
                <div>{this.props.slots.slot1[0]}</div>
                <div>{this.props.slots.slot2[0]}</div>
            </div>
        );
    }
}
