/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IMaribFirstContainerData } from './marib-first-container.data';
import { IMaribFirstContainerProps } from './marib-first-container.props.autogenerated';

export interface IMaribFirstContainerViewProps extends IMaribFirstContainerProps<IMaribFirstContainerData> {

}

/**
 *
 * MaribFirstContainer component
 * @extends {React.PureComponent<IMaribFirstContainerProps<IMaribFirstContainerData>>}
 */
class MaribFirstContainer extends React.PureComponent<IMaribFirstContainerProps<IMaribFirstContainerData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default MaribFirstContainer;
