/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import SecondContainer from '../second-container';
import { ISecondContainerData } from '../second-container.data';
import {
  ISecondContainerConfig,
  ISecondContainerProps
} from '../second-container.props.autogenerated';

const mockData: ISecondContainerData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: ISecondContainerConfig = {
  showText: 'second-container'
};

const mockActions = {};

describe('SecondContainer', () => {
  let moduleProps: ISecondContainerProps<ISecondContainerData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as ISecondContainerProps<ISecondContainerData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <SecondContainer {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
